### ISSUE TITLE
tag: content property is invalid in generated css/scss

### ISSUE THREAD

**Issue by willsoto** [pluralsight/design-system#231]
## Bug

Empty string for `content` css property seems to be stripped. Sass is then unable to compile the file. See:

- https://github.com/pluralsight/design-system/blob/e7f8b7188b5b1b51ec60841ace95ce5829a77173/packages/tag/src/css/index.js#L36
- https://github.com/pluralsight/design-system/blob/e7f8b7188b5b1b51ec60841ace95ce5829a77173/packages/tag/src/css/index.js#L58

```bash
cat node_modules/@pluralsight/ps-design-system-tag/dist/css/index.scss
```

Truncated for brevity:

```css
.psds-tag--clickable:focus:before, .psds-tag--clickable.psds-tag--error:before {
  content:  ;
  position: absolute;
  top: -1px;
  left: -1px;
  right: -1px;
  bottom: -1px;
  background: #000000;
  z-index: -1;
  border-radius: 16px;
}

/* ... */

.psds-tag--clickable:focus:after, .psds-tag--clickable.psds-tag--error:after {
  content:  ;
  position: absolute;
  top: -4px;
  left: -4px;
  right: -4px;
  bottom: -4px;
  z-index: -2;
  border-radius: 18px;
}
```

### Expected behavior

Sass can compile generated stylesheets successfully.

### Actual behavior

Sass can't compile stylesheet:

```
Module build failed (from ./node_modules/sass-loader/lib/loader.js):

  content:  ;
        ^
      Style declaration must contain a value
      in node_modules/@pluralsight/ps-design-system-tag/dist/css/index.scss (line 24, column 10)
```

### Steps to repro

1. Install node-sass and ps-design-system-tag
2. `node-sass node_modules/@pluralsight/ps-design-system-tag/dist/css/index.scss`

### Related packages

- tag@1.6.1

### Environment

- OS - MacOS 10.13.5
- Browser version - Chrome 68

### Additional Information

I can kinda workaround this currently by using the CSS. I suspect this only works because CSS _ignores_ invalid / unknown properties. The error state doesn't seem to work when I attempt to implement this locally though.
